# Generated by Django 5.0.7 on 2024-07-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cat_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='toy',
            new_name='toys',
        ),
    ]
